# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/ma4444sl-s/project_2/project_2.cache/wt [current_project]
set_property parent.project_path C:/Users/ma4444sl-s/project_2/project_2.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:nexys4:part0:1.1 [current_project]
read_vhdl -library xil_defaultlib {
  {//puma.student.lth.se/ma4444sl-s/Windows/Desktop/Lab 2/binary_to_sg.vhd}
  {//puma.student.lth.se/ma4444sl-s/Windows/Desktop/Lab 2/convert_to_binary.vhd}
  {//puma.student.lth.se/ma4444sl-s/Windows/Desktop/Lab 2/keyboard_ctrl.vhd}
  {//puma.student.lth.se/ma4444sl-s/Windows/Desktop/Lab 2/edge_detector.vhd}
  {//puma.student.lth.se/ma4444sl-s/Windows/Desktop/Lab 2/sync_keyboard.vhd}
  {//puma.student.lth.se/ma4444sl-s/Windows/Desktop/Lab 2/convert_scancode.vhd}
  {//puma.student.lth.se/ma4444sl-s/Windows/Desktop/Lab 2/keyboard_top.vhd}
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc {{//puma.student.lth.se/ma4444sl-s/Windows/Desktop/Lab 2/keyboard_top.xdc}}
set_property used_in_implementation false [get_files {{//puma.student.lth.se/ma4444sl-s/Windows/Desktop/Lab 2/keyboard_top.xdc}}]


synth_design -top keyboard_top -part xc7a100tcsg324-1


write_checkpoint -force -noxdef keyboard_top.dcp

catch { report_utilization -file keyboard_top_utilization_synth.rpt -pb keyboard_top_utilization_synth.pb }
